# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'giaodienbtlXLA.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.selectImage = QtWidgets.QPushButton(self.centralwidget)
        self.selectImage.setGeometry(QtCore.QRect(30, 450, 93, 28))
        self.selectImage.setObjectName("selectImage")
        self.inputImage = QtWidgets.QLabel(self.centralwidget)
        self.inputImage.setGeometry(QtCore.QRect(40, 70, 291, 291))
        self.inputImage.setText("")
        self.inputImage.setScaledContents(True)
        self.inputImage.setObjectName("inputImage")
        self.outputImage = QtWidgets.QLabel(self.centralwidget)
        self.outputImage.setGeometry(QtCore.QRect(440, 70, 281, 291))
        self.outputImage.setLineWidth(1)
        self.outputImage.setText("")
        self.outputImage.setScaledContents(True)
        self.outputImage.setObjectName("outputImage")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 20, 81, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(560, 20, 81, 20))
        self.label_3.setObjectName("label_3")
        self.selectVideo = QtWidgets.QPushButton(self.centralwidget)
        self.selectVideo.setGeometry(QtCore.QRect(140, 450, 93, 28))
        self.selectVideo.setObjectName("selectVideo")
        self.btnRun = QtWidgets.QPushButton(self.centralwidget)
        self.btnRun.setGeometry(QtCore.QRect(510, 440, 93, 28))
        self.btnRun.setObjectName("btnRun")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.selectImage.setText(_translate("MainWindow", "selectImage"))
        self.label_2.setText(_translate("MainWindow", "INPUT"))
        self.label_3.setText(_translate("MainWindow", "OUTPUT"))
        self.selectVideo.setText(_translate("MainWindow", "selectVideo"))
        self.btnRun.setText(_translate("MainWindow", "Run"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
